### ISSUE TITLE
README is incorrect

### ISSUE THREAD

**Issue by victornoel** [dropwizard-bundles/dropwizard-configurable-assets-bundle#26]
In the README, it is written:

``` java
public class SampleConfiguration extends Configuration implements AssetsBundleConfiguration {
  @Valid
  @NotNull
  @JsonProperty
  private final AssetsConfiguration assets = new AssetsConfiguration();

  @Override
  public AssetsConfiguration getAssetsConfiguration() {
    return assets;
  }
}
```

But it can't work because `AssetsConfiguration` has no public constructor!

What is the correct way of using it?

**Comment by nbauernfeind** [comment]
Good call, that issue was introduced in this commit: https://github.com/dropwizard-bundles/dropwizard-configurable-assets-bundle/commit/fb57a1d1c3e803bdb06d30765fffcf96dd39357c

For the next release I will add back in a public default constructor.

For now you can use: `AssetsConfiguration.builder().build();`

**Comment by victornoel** [comment]
Ok, that's what I used in the end :) thanks and glad to be of use :)
