### ISSUE TITLE
Authentication Hook For Assets

### ISSUE THREAD

**Issue by 0x9090** [dropwizard-bundles/dropwizard-configurable-assets-bundle#40]
I am wondering what the recommended way to add AuthZ/AuthN to the ConfiguredAssetsBundle is. My understanding is that AssetBundles are separate servlets, and would not natively work with Jersey request filters or Dropwizard custom authentication.

My use-case is: a user on a multi-tennanted app can upload a file, and then that file is served back to them with ConfiguredAssetsBundle, after an Auth check.

https://stackoverflow.com/questions/39567783/jersey-containerresponsefilter-not-applied-to-all-responses

**Comment by mattmetlis** [comment]
I don't have an answer to your question, but be warned that as best I can tell this project is abandoned. I submitted 2 tickets and a PR in 2019 and got no response at all, of any kind. It's also been 3 years since any PRs have been merged.

I switched my projects from using this to using the assets bundle that is part of the Dropwizard project. I find this project misleadingly named - it's not the official Dropwizard project.

**Comment by 0x9090** [comment]
> 
> 
> I don't have an answer to your question, but be warned that as best I can tell this project is abandoned. I submitted 2 tickets and a PR in 2019 and got no response at all, of any kind. It's also been 3 years since any PRs have been merged.
> 
> I switched my projects from using this to using the assets bundle that is part of the Dropwizard project. I find this project misleadingly named - it's not the official Dropwizard project.

Thanks for the heads up
