### ISSUE TITLE
/api for resources,  /* for assets  - a query.

### ISSUE THREAD

**Issue by solmetricchris** [dropwizard-bundles/dropwizard-configurable-assets-bundle#7]
I'd like to have the following setup:

/api      send data into my various dropwizard resources.

/\*   goes  to /src/main/resources/assets

currently I have

server:
  rootPath: /api

in my config.yml  which put the resources into the /api  space.

and I have

```
    bootstrap.addBundle(new ConfiguredAssetsBundle("/assets/", "/"));
```

which should put the assets into /*

on startup dropwizard appears to tell me that my resources are appearing in the /api space.

However,  when I do a simple GET against one of those APIs, I get HTTP/1.1 404 Not Found

ideas ?

**Comment by nbauernfeind** [comment]
Yes, that is the current expected behavior. Dropwizard is sending all of your requests to the AssetsServlet because it is the first mapping that matches every request. It is not possible to notify Dropwizard that it should try to match against another URL pattern because "the request should not have gone to this servlet".

We've been debating whether or not to rewrite the bundle to use a filter instead of a servlet which would allow the use case that you're describing. However, you then have to be careful to not accidentally bleed some asset path on top of your resource. If you had a resource w/Path "/data/{id}" and mapped the assets bundle to "/*" then if you had an assets file in "data/my_magic_id" then it would serve up the file instead of hitting the resource.

.. Or maybe we should just offer both implementations.

A work around that should work for you is to use the multiple mappings constructor and map all of your directories/files to at least one level deep.

``` java
        bootstrap.addBundle(new ConfiguredAssetsBundle(
            ImmutableMap.<String, String>builder()
                .put("/assets/index.html", "/index.html")
                .put("/assets/css/", "/css/")
                ...
                .build()
        ));
```

**Comment by solmetricchris** [comment]
I realized finally that I had a configuration issue. Specifically the  YML file should have NOT have read:

server:
   rootPath: /api

BUT rather this file should have had:

server:
  rootPath: /api/*

In this way thing work the way I want.

**Comment by nbauernfeind** [comment]
That's great news!
